import type { SeedGroup } from "./types";

// Channel UUIDs
const CH_KIT = "70209dd4-e94d-481e-b46c-1644b6659d34"; // kit-parcalari
const CH_PIT = "92de2aa2-3a61-4928-b16f-9cde02d59ff6"; // pit-ekibi
const CH_GUV = "8fd2d7d3-bc40-446b-94b3-38b9ed4b9ec2"; // guvenlik

// User UUIDs
const U_BUGRA = "aad122b8-7776-42c4-b9d7-51b6aa3ecf67"; // lead mentor (real)
const U_HAKAN = "18cb0c6b-5104-421d-a71c-828f2867c479";
const U_AYSE = "2ac6551e-a2b4-4698-a73e-604bcaff5225";
const U_KAGAN = "d5f5c1f1-59dc-4c58-ba1e-5ed213490492";
const U_YAGIZ = "77c39129-e3dd-4586-ba7f-91cf405766dc";
const U_MEHMET = "f36056dd-998e-4048-a67a-43b54540bd2e";
const U_FATMA = "e19b8805-8559-44db-8251-f640a519e3e2";
const U_DENIZ = "69af37aa-117c-4e1c-a330-968ee1bd0982"; // captain
const U_ALI = "9b049271-118e-446a-a624-7623fc9f9206";
const U_ZEYNEP = "8590cff9-8649-4448-a4f6-a8d72ad45885";
const U_CAN = "404e74a7-ceaa-4f79-b7c9-bcf347151613";
const U_ELIF = "2de90e33-54ce-43f3-af8e-66ce82d5b2bf";
const U_EREN = "db5376b7-cd4a-46af-a2ca-98a01b25c9de";
const U_MERVE = "8297b7d3-0d1e-42b9-a579-ba6414bb0a94";

export const group: SeedGroup = {
  groupName: "build-ops",
  messages: [
    // ============================================================
    // #kit-parcalari — KOP unboxing, missing parts, COTS approval
    // ============================================================
    {
      localId: "kop-001",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "KOP shipment landed in Çerkezköy! We're doing the unboxing tomorrow at 09:30 in the shop — anyone who wants to come is welcome 📦",
      createdAt: "2026-01-09T18:42:00+03:00",
    },
    {
      localId: "kop-002",
      channelId: CH_KIT,
      authorUserId: U_ALI,
      content: "I'm in — should we film it? Would be good content for #medya",
      createdAt: "2026-01-09T18:48:00+03:00",
      replyToLocalId: "kop-001",
    },
    {
      localId: "kop-003",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "@Merve please film the unboxing. For every box I want a packing slip + contents photo so we can verify nothing's missing.",
      createdAt: "2026-01-09T18:52:00+03:00",
      replyToLocalId: "kop-002",
    },
    {
      localId: "kop-004",
      channelId: CH_KIT,
      authorUserId: U_MERVE,
      content: "got it, GoPro is ready. setting up the tripod now",
      createdAt: "2026-01-09T19:01:00+03:00",
      replyToLocalId: "kop-003",
    },
    {
      localId: "kop-005",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "Unboxing done. First inventory notes:\n- **Kraken X60**: expected 8, only **6** in the box ❌\n- **REV Sparkmax**: 12/12 ✅\n- **MRF radio**: 1/1 ✅\n- **MTC backup battery**: 2/2 ✅\n- **AndyMark NEO**: 4/4 ✅\n- **Cable management kit**: looks like half is missing, need to recount\n\nI'll open a ticket with FIRST about the Krakens — packing slip says 8 but the box only has 6.",
      createdAt: "2026-01-10T11:23:00+03:00",
    },
    {
      localId: "kop-006",
      channelId: CH_KIT,
      authorUserId: U_HAKAN,
      content: "Include a side-by-side photo of the packing slip vs the actual count in the email. FIRST replacement turnaround is usually 3-5 business days. CC me on the email.",
      createdAt: "2026-01-10T11:31:00+03:00",
      replyToLocalId: "kop-005",
    },
    {
      localId: "kop-007",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "Email sent — FIRST Inventory Discrepancy form attached, packing slip scanned, plus the in-box photos. Ticket #INV-2026-1184 is open.",
      createdAt: "2026-01-10T13:55:00+03:00",
      replyToLocalId: "kop-006",
    },
    {
      localId: "kop-008",
      channelId: CH_KIT,
      authorUserId: null,
      agentGenerated: true,
      agentType: "channel-agent",
      juryReflexKind: "proof_demand",
      content: "Nice paper trail on the missing parts — packing slip + photos + ticket number. This is exactly the kind of \"process discipline\" example that lands in the end-of-season Impact narrative. When the replacement arrives, please drop a \"closed\" note in this same thread. — PitOS",
      createdAt: "2026-01-10T14:02:00+03:00",
      replyToLocalId: "kop-007",
    },
    {
      localId: "kop-009",
      channelId: CH_KIT,
      authorUserId: U_CAN,
      content: "Final count on the cable management kit: PWM cables were supposed to come as a 6-pack, only **3** arrived. CAN bus terminator 2/2, all good.",
      createdAt: "2026-01-10T16:40:00+03:00",
      replyToLocalId: "kop-005",
    },
    {
      localId: "kop-010",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "Added the PWM to the list, attached it to the FIRST ticket. We're now short 2 items: 2 Krakens + 3 PWM. Total value ~$320.",
      createdAt: "2026-01-10T16:48:00+03:00",
      replyToLocalId: "kop-009",
    },
    {
      localId: "kop-011",
      channelId: CH_KIT,
      authorUserId: U_EREN,
      content: "From the mechanical side — we still haven't decided **MAXSwerve vs SDS MK4i** for swerve modules. @Zeynep is modeling both versions in CAD but parts ordering will be blocked by tomorrow.",
      createdAt: "2026-01-12T10:15:00+03:00",
    },
    {
      localId: "kop-012",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "@Yağız what's your call as a mentor? Our COTS budget has $1800 for one of them, we can't afford both.",
      createdAt: "2026-01-12T10:28:00+03:00",
      replyToLocalId: "kop-011",
    },
    {
      localId: "kop-013",
      channelId: CH_KIT,
      authorUserId: U_YAGIZ,
      content: "Two criteria:\n1. **Compatibility with existing inventory** — we have SDS MK4i flanges and bevel gears left over from last season, so we're not starting from zero.\n2. **Lead time** — MK4i via AndyMark is 7-10 days, MAXSwerve direct from REV is 14+ days to TR.\n\nI'm leaning MK4i but let's wait for Zeynep's CAD comparison and look at the dimensions.",
      createdAt: "2026-01-12T11:02:00+03:00",
      replyToLocalId: "kop-012",
    },
    {
      localId: "kop-014",
      channelId: CH_KIT,
      authorUserId: U_ZEYNEP,
      content: "CAD comparison done, Onshape link: `goat8092/swerve-compare-2026`. Summary:\n- MK4i: compatible with our existing plates, 4 modules → ~$1620\n- MAXSwerve: needs new bumper plates, 4 modules → ~$1740 + plate cost\n\nBudget-wise, MK4i wins. Weight difference is ~140g per module, negligible.",
      createdAt: "2026-01-12T19:33:00+03:00",
      replyToLocalId: "kop-013",
    },
    {
      localId: "kop-015",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "**Decision: SDS MK4i x4 → ordering through AndyMark.** Need mentor sign-off from @Hakan and @Yağız.",
      createdAt: "2026-01-12T19:48:00+03:00",
      replyToLocalId: "kop-014",
    },
    {
      localId: "kop-016",
      channelId: CH_KIT,
      authorUserId: U_HAKAN,
      content: "Approved. Drop the PO into the COTS Tracker on Notion, and run the QC checklist when the shipment arrives.",
      createdAt: "2026-01-12T20:11:00+03:00",
      replyToLocalId: "kop-015",
    },
    {
      localId: "kop-017",
      channelId: CH_KIT,
      authorUserId: U_YAGIZ,
      content: "Approved +1. While we're at it, let's talk AndyMark vs WCP — this season we're placing 3 orders with AndyMark and 1 with WCP. WCP quality is good but customs to TR averages 2 weeks. Let's nail down our default supplier policy.",
      createdAt: "2026-01-12T20:18:00+03:00",
      replyToLocalId: "kop-016",
    },
    {
      localId: "kop-018",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "Last season's data: AndyMark 7 orders averaged 9 days, WCP 3 orders averaged 17 days, one took 23 days (the bumper corners). Defaulting to AndyMark makes sense, with WCP only for parts that don't have an equivalent.",
      createdAt: "2026-01-12T20:31:00+03:00",
      replyToLocalId: "kop-017",
    },
    {
      localId: "kop-019",
      channelId: CH_KIT,
      authorUserId: U_HAKAN,
      content: "**Policy:** Default COTS supplier is **AndyMark**. WCP only for WCP-exclusive parts (custom pulleys, Falcon trim kits). REV direct from REV.com. Orders ≥ $500 require 3 mentor approvals.",
      createdAt: "2026-01-12T20:42:00+03:00",
      replyToLocalId: "kop-018",
    },
    {
      localId: "kop-020",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "Updated the **Procurement Policy** page on Notion. Every student needs to read it and ✅, I sent it as a DM.",
      createdAt: "2026-01-12T21:05:00+03:00",
      replyToLocalId: "kop-019",
    },
    {
      localId: "kop-021",
      channelId: CH_KIT,
      authorUserId: U_ELIF,
      content: "We need a backup pneumatic regulator — the leftover one from last season mostly works but one of them leaks. AndyMark `am-2622`, $24. Can I get approval?",
      createdAt: "2026-01-15T14:22:00+03:00",
    },
    {
      localId: "kop-022",
      channelId: CH_KIT,
      authorUserId: U_HAKAN,
      content: "Under $500, single mentor approval is enough — approved. Add it to the PO.",
      createdAt: "2026-01-15T14:34:00+03:00",
      replyToLocalId: "kop-021",
    },
    {
      localId: "kop-023",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "FIRST INV-2026-1184 update: the 2 Kraken X60s and 3 PWM cables have **shipped**, tracking is in. ETA Jan 22.",
      createdAt: "2026-01-18T10:08:00+03:00",
      replyToLocalId: "kop-007",
    },
    {
      localId: "kop-024",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "Replacement landed, afternoon of Jan 22. Krakens 2/2, PWM 3/3, ticket closed ✅",
      createdAt: "2026-01-22T15:47:00+03:00",
      replyToLocalId: "kop-023",
    },
    {
      localId: "kop-025",
      channelId: CH_KIT,
      authorUserId: U_CAN,
      content: "We covered the Kraken stuff in #elektrik and updated the CAN ID scheme for the motor controllers too. We can mark this thread closed.",
      createdAt: "2026-01-22T16:12:00+03:00",
      replyToLocalId: "kop-024",
    },
    {
      localId: "kop-026",
      channelId: CH_KIT,
      authorUserId: U_AYSE,
      content: "Is the KOP inventory table up to date on Notion? I need a parts list with values for the sponsor report **by Jan 27**.",
      createdAt: "2026-01-24T09:30:00+03:00",
    },
    {
      localId: "kop-027",
      channelId: CH_KIT,
      authorUserId: U_DENIZ,
      content: "@Eren the inventory table was on you. Is it ready?",
      createdAt: "2026-01-24T09:42:00+03:00",
      replyToLocalId: "kop-026",
    },
    {
      localId: "kop-028",
      channelId: CH_KIT,
      authorUserId: U_EREN,
      content: "Wrapping it up today, I'll post the link tonight at 21:00. KOP contents + COTS purchases + donated parts (Siemens sent us a bearing kit) all on separate sheets.",
      createdAt: "2026-01-24T09:51:00+03:00",
      replyToLocalId: "kop-027",
    },
    {
      localId: "kop-029",
      channelId: CH_KIT,
      authorUserId: U_EREN,
      content: "Done: `goat8092 / KOP-Inventory 2026.xlsx`. 187 SKUs total, 4 main categories. I added a pivot for the sponsor report too.",
      createdAt: "2026-01-24T20:54:00+03:00",
      replyToLocalId: "kop-028",
    },
    {
      localId: "kop-030",
      channelId: CH_KIT,
      authorUserId: U_AYSE,
      content: "Perfect. I'm putting together dedicated pages for Boeing and Siemens — pulling shelf-life and where-it's-used info on their donated parts straight from this 👍",
      createdAt: "2026-01-25T08:11:00+03:00",
      replyToLocalId: "kop-029",
    },

    // ============================================================
    // #pit-ekibi — Bosphorus pit setup, 6-min turnaround, tools
    // ============================================================
    {
      localId: "pit-001",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "Bosphorus Regional **Mar 6-8** 🏁 Form for pit crew roles: https://forms.goat8092.tr/pit-2026 — fill it out **by Feb 20**.",
      createdAt: "2026-02-12T18:30:00+03:00",
    },
    {
      localId: "pit-002",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "Pit crew positions (excluding drive team):\n- **Pit Captain** — coordination (me)\n- **Safety Captain** — safety checks, FRC inspection\n- **Mechanical 1-2** — fast repairs\n- **Electrical 1** — wiring/fuses/CAN bus\n- **Software 1** — laptop, deploys\n- **Tools/Inventory** — tool wall, parts tracking\n- **Pit Display/PR** — talking to visitors, escorting judges",
      createdAt: "2026-02-12T18:38:00+03:00",
      replyToLocalId: "pit-001",
    },
    {
      localId: "pit-003",
      channelId: CH_PIT,
      authorUserId: U_ALI,
      content: "I'm in for Mechanical 1. Last season at the regional we got bumper swap under 4 min — this season I'm aiming for 3 min 🔧",
      createdAt: "2026-02-12T19:15:00+03:00",
      replyToLocalId: "pit-002",
    },
    {
      localId: "pit-004",
      channelId: CH_PIT,
      authorUserId: U_CAN,
      content: "Electrical 1 — I'll take it. Bringing 2 spare CAN bus terminators, plus spares for the fuse panel across all the values.",
      createdAt: "2026-02-12T19:22:00+03:00",
      replyToLocalId: "pit-002",
    },
    {
      localId: "pit-005",
      channelId: CH_PIT,
      authorUserId: U_ELIF,
      content: "Software 1 — laptop is mine. Are we taking **two** laptops or just one? A backup would be smart, an HDMI port died on us last year.",
      createdAt: "2026-02-12T19:28:00+03:00",
      replyToLocalId: "pit-002",
    },
    {
      localId: "pit-006",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "Two laptops +1, I was thinking the same. We'll use Eren's laptop as backup and clone the image ahead of time.",
      createdAt: "2026-02-12T19:35:00+03:00",
      replyToLocalId: "pit-005",
    },
    {
      localId: "pit-007",
      channelId: CH_PIT,
      authorUserId: U_ZEYNEP,
      content: "I'd like to take Safety Captain. I helped with safety checks last season and I know the FRC inspection process.",
      createdAt: "2026-02-13T11:08:00+03:00",
      replyToLocalId: "pit-002",
    },
    {
      localId: "pit-008",
      channelId: CH_PIT,
      authorUserId: U_MERVE,
      content: "I can do Pit Display/PR + Tools/Inventory — I think I can juggle both depending on match frequency.",
      createdAt: "2026-02-13T11:22:00+03:00",
      replyToLocalId: "pit-002",
    },
    {
      localId: "pit-009",
      channelId: CH_PIT,
      authorUserId: U_HAKAN,
      content: "You realize both roles need full attention, right? Tools/Inventory means catching a missing tool within 60 seconds; PR means a judge can occupy you for 8 minutes. **Pick one**, assign another student to the other.",
      createdAt: "2026-02-13T11:30:00+03:00",
      replyToLocalId: "pit-008",
    },
    {
      localId: "pit-010",
      channelId: CH_PIT,
      authorUserId: U_MERVE,
      content: "Fair point, I'll take Tools/Inventory. I'd suggest Eren for PR, his presentation skills are strong.",
      createdAt: "2026-02-13T11:48:00+03:00",
      replyToLocalId: "pit-009",
    },
    {
      localId: "pit-011",
      channelId: CH_PIT,
      authorUserId: U_EREN,
      content: "I'm in for Pit Display/PR 🎤 I'll prep the judge briefing cards with Impact talking points.",
      createdAt: "2026-02-13T12:01:00+03:00",
      replyToLocalId: "pit-010",
    },
    {
      localId: "pit-012",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "Roles:\n- Pit Captain: Deniz\n- Safety: Zeynep\n- Mechanical 1: Ali, Mechanical 2: (open — anyone?)\n- Electrical 1: Can\n- Software 1: Elif\n- Tools/Inventory: Merve\n- Pit Display/PR: Eren\n\nWe still need someone for Mechanical 2.",
      createdAt: "2026-02-13T12:18:00+03:00",
    },
    {
      localId: "pit-013",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "**6-minute repair drill:** end of match → into pit → checklist → repair → back out to the queue. Saturday at 14:00 in the shop. First-pass goal 8 min, end-of-season goal 6 min.",
      createdAt: "2026-02-15T20:12:00+03:00",
    },
    {
      localId: "pit-014",
      channelId: CH_PIT,
      authorUserId: U_ALI,
      content: "First run: **9 min 12 sec**. Bumper removal 1:40, battery swap 0:55, intake alignment 4:30 (the longest), bumper reattach 1:55.",
      createdAt: "2026-02-21T15:48:00+03:00",
      replyToLocalId: "pit-013",
    },
    {
      localId: "pit-015",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "Intake alignment is the bottleneck. @Ali can you check if two turn-buckles could shave 30 sec off, and have mechanical build us a jig?",
      createdAt: "2026-02-21T15:55:00+03:00",
      replyToLocalId: "pit-014",
    },
    {
      localId: "pit-016",
      channelId: CH_PIT,
      authorUserId: U_ALI,
      content: "Jig is built, single-bolt alignment. Second run: **6 min 48 sec** 🎯 close to target.",
      createdAt: "2026-02-22T17:22:00+03:00",
      replyToLocalId: "pit-015",
    },
    {
      localId: "pit-017",
      channelId: CH_PIT,
      authorUserId: U_YAGIZ,
      content: "Great progress. One note: try the drill under a **back-to-back match scenario** too — 2 matches in a row + a surprise electrical issue squeezed in between. At a real regional the calls keep stacking.",
      createdAt: "2026-02-22T18:30:00+03:00",
      replyToLocalId: "pit-016",
    },
    {
      localId: "pit-018",
      channelId: CH_PIT,
      authorUserId: U_MERVE,
      content: "**Tool wall photo** taken, labels are done: https://drive.goat.../tool-wall-2026.jpg\n\nRed tag = missing/lost. We have 2 reds right now:\n- 5/16\" hex L-key\n- Small zip-tie cutter scissors\n\nMissing in the shop. If we don't find them I'll order replacements.",
      createdAt: "2026-02-25T11:15:00+03:00",
    },
    {
      localId: "pit-019",
      channelId: CH_PIT,
      authorUserId: U_CAN,
      content: "The L-key might be on me, I think I dropped it in my bag during assembly. I'll check and get back, sorry 😅",
      createdAt: "2026-02-25T11:22:00+03:00",
      replyToLocalId: "pit-018",
    },
    {
      localId: "pit-020",
      channelId: CH_PIT,
      authorUserId: U_CAN,
      content: "Found it, put it back. Tool wall = 1 red left.",
      createdAt: "2026-02-25T13:08:00+03:00",
      replyToLocalId: "pit-019",
    },
    {
      localId: "pit-021",
      channelId: CH_PIT,
      authorUserId: U_MERVE,
      content: "Ordered replacement scissors, 2 coming from AndyMark. This time I'm clipping every tool to the wall with carabiners — they're not going anywhere 🔗",
      createdAt: "2026-02-26T10:42:00+03:00",
      replyToLocalId: "pit-018",
    },
    {
      localId: "pit-022",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "**Pit display board** content list (4 panels):\n1. Robot tech summary — dimensions, weight, capabilities\n2. Season storyline — autonomous → endgame\n3. Team identity — G.O.A.T., Tekirdağ, sponsors\n4. Impact page — outreach metrics, G.O.A.T. Jr.\n\n@Merve and @Eren are running design together, print deadline is Mar 1.",
      createdAt: "2026-02-27T16:00:00+03:00",
    },
    {
      localId: "pit-023",
      channelId: CH_PIT,
      authorUserId: U_EREN,
      content: "Mockup is up: https://figma.com/.../pit-board-2026 — looking for feedback.",
      createdAt: "2026-02-28T22:14:00+03:00",
      replyToLocalId: "pit-022",
    },
    {
      localId: "pit-024",
      channelId: CH_PIT,
      authorUserId: U_BUGRA,
      content: "Design looks great. Two notes:\n- Line the sponsor logos along the bottom of panel 4 too (better visibility)\n- For the outreach metrics, @Ayşe has the latest numbers — 412 students went to 487 last week",
      createdAt: "2026-03-01T09:45:00+03:00",
      replyToLocalId: "pit-023",
    },
    {
      localId: "pit-025",
      channelId: CH_PIT,
      authorUserId: U_EREN,
      content: "Updated and sent to print. Pickup tomorrow evening.",
      createdAt: "2026-03-01T14:20:00+03:00",
      replyToLocalId: "pit-024",
    },
    {
      localId: "pit-026",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "Pit setup checklist (the moment we hit the venue):\n- [ ] Tool wall installed\n- [ ] Battery cart positioned (3 batteries + charger)\n- [ ] Laptop x2 + ethernet\n- [ ] First aid kit visible\n- [ ] Display board, 4 panels\n- [ ] Brand banner (purple background, G.O.A.T. logo)\n- [ ] Sponsor sticker layer\n- [ ] Emergency stop button visible\n\nPit goes up the evening of Mar 5, inspection morning of Mar 6.",
      createdAt: "2026-03-04T19:00:00+03:00",
    },
    {
      localId: "pit-027",
      channelId: CH_PIT,
      authorUserId: U_ZEYNEP,
      content: "For inspection: full bumper color set, certified weight scale, pneumatic schematic printed, electrical schematic printed, robot rules form signed. As soon as we get to the venue let's put the robot on the scale before any line forms.",
      createdAt: "2026-03-04T19:18:00+03:00",
      replyToLocalId: "pit-026",
    },
    {
      localId: "pit-028",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "Pit is up! Display board install pics: https://drive.goat.../pit-2026-day0.jpg\n\nOur neighbor is 6800 (İstanbul), across from us is 7426. Said hi to both 👋",
      createdAt: "2026-03-05T22:30:00+03:00",
    },
    {
      localId: "pit-029",
      channelId: CH_PIT,
      authorUserId: U_ALI,
      content: "Intake snap broke after Q12, fixed it in 5 min 40 sec 💪 used the spare bracket, postmortem going up in #mekanik.",
      createdAt: "2026-03-06T14:55:00+03:00",
    },
    {
      localId: "pit-030",
      channelId: CH_PIT,
      authorUserId: U_DENIZ,
      content: "Under target! The drills paid off 🎯 @Zeynep also passed the safety check, refs signed off.",
      createdAt: "2026-03-06T15:02:00+03:00",
      replyToLocalId: "pit-029",
    },
    {
      localId: "pit-031",
      channelId: CH_PIT,
      authorUserId: null,
      agentGenerated: true,
      agentType: "channel-agent",
      juryReflexKind: "why_question",
      content: "Drills went 9:12 → 6:48 → 5:40 in competition. Let's document this learning curve for Impact — \"3 weeks, 3 simulations, 4 minutes of improvement\". @Eren keep this in your PR back pocket — judges love it when you answer with data. — PitOS",
      createdAt: "2026-03-06T15:14:00+03:00",
      replyToLocalId: "pit-030",
    },
    {
      localId: "pit-032",
      channelId: CH_PIT,
      authorUserId: U_MERVE,
      content: "Tool wall final state (day 3): 0 red tags. The carabiner system worked, not a single tool went missing 👏",
      createdAt: "2026-03-08T17:40:00+03:00",
    },

    // ============================================================
    // #guvenlik — battery acid, near-miss, LOTO, safety walks
    // ============================================================
    {
      localId: "guv-001",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Tomorrow at 14:00, **battery acid spill drill** in the shop. Attendance is mandatory for every student. Bring gloves and goggles — we're walking through the baking soda / coolant neutralization procedure hands-on.",
      createdAt: "2025-09-17T19:30:00+03:00",
    },
    {
      localId: "guv-002",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Materials list (I'm bringing these as the mentor):\n- 2 SLA test batteries (pre-leaked)\n- 2kg baking soda\n- 12 pairs of acid-resistant gloves\n- 4 face shields\n- pH / staining indicator paper\n- **No real electrolyte** during the drill — we're using a simulant",
      createdAt: "2025-09-17T19:38:00+03:00",
      replyToLocalId: "guv-001",
    },
    {
      localId: "guv-003",
      channelId: CH_GUV,
      authorUserId: U_DENIZ,
      content: "Got everyone signed in — 14 students + 3 mentors confirmed. There's a short quiz after the drill, right?",
      createdAt: "2025-09-17T20:05:00+03:00",
      replyToLocalId: "guv-002",
    },
    {
      localId: "guv-004",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Yes, 8 questions. Pass mark is 6/8. Anyone who doesn't pass can't enter the battery area unsupervised until the next drill — that's the rule.",
      createdAt: "2025-09-17T20:12:00+03:00",
      replyToLocalId: "guv-003",
    },
    {
      localId: "guv-005",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Drill done ✅ 14 students attended, 13 passed the quiz on the first try. 1 student needs a retake, scheduled for Thursday.\n\n**Critical finding:** the eyewash bottle at the shop battery station is past its expiration date. Ordered a replacement today.",
      createdAt: "2025-09-18T17:20:00+03:00",
    },
    {
      localId: "guv-006",
      channelId: CH_GUV,
      authorUserId: U_HAKAN,
      content: "Good catch. Let's set up a **quarterly inspection schedule** for the eyewash and first aid kit — expiration dates, missing supplies, accessibility. @Kağan can you design the format?",
      createdAt: "2025-09-18T17:35:00+03:00",
      replyToLocalId: "guv-005",
    },
    {
      localId: "guv-007",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Designed it. Set up a **Safety Inventory Audit** page in Notion. Last week of each quarter, mentor + 1 student paired up. First audit: Dec 28.",
      createdAt: "2025-09-19T11:08:00+03:00",
      replyToLocalId: "guv-006",
    },
    {
      localId: "guv-008",
      channelId: CH_GUV,
      authorUserId: U_BUGRA,
      content: "This is the foundation of safety culture — not enforcement, **habit**. Let's run the audits openly, rotate students through them across the year. Makes a great anchor for Impact too.",
      createdAt: "2025-09-19T13:42:00+03:00",
      replyToLocalId: "guv-007",
    },
    {
      localId: "guv-009",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "**Shop safety walk** results — Sep 24:\n- ✅ Emergency exit signs clear\n- ✅ Fire extinguisher accessible, pressure good\n- ⚠️ Cable mess around the mechanical bench (trip hazard)\n- ❌ Soldering station ventilation fan not working\n- ✅ Battery charging area is isolated\n\nI asked Çetin Group (sponsor) for technician support to fix the fan, they'll come this week.",
      createdAt: "2025-09-24T18:00:00+03:00",
    },
    {
      localId: "guv-010",
      channelId: CH_GUV,
      authorUserId: U_DENIZ,
      content: "@Ali and I cleaned up the cable mess in an hour, ran it through cable channels. Photo: https://drive.goat.../shop-cabling.jpg ✅",
      createdAt: "2025-09-25T19:30:00+03:00",
      replyToLocalId: "guv-009",
    },
    {
      localId: "guv-011",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Fan fixed (Çetin Group's technician swapped it in 2 hours). Soldering station is back up, ventilation flow rate measured — above FRC standard 👍",
      createdAt: "2025-09-29T16:45:00+03:00",
      replyToLocalId: "guv-009",
    },
    {
      localId: "guv-012",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "**Eye protection enforcement** — I caught 3 students without goggles in the shop this week. Working at the bench / dremel / soldering area **without goggles** is not acceptable. Reminder: rule is being tightened — students without goggles cannot enter these zones.",
      createdAt: "2025-11-08T20:15:00+03:00",
    },
    {
      localId: "guv-013",
      channelId: CH_GUV,
      authorUserId: U_DENIZ,
      content: "Understood. The pit crew also needs a standard goggles list for competitions. I'll buy 20 Z87.1-rated spares for the case.",
      createdAt: "2025-11-08T20:28:00+03:00",
      replyToLocalId: "guv-012",
    },
    {
      localId: "guv-014",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "**Q4 safety audit (Dec 28) results:** First aid kit was missing gauze, restocked. Eyewash full, expires 2027. Two fire extinguishers serviced. Glove inventory at 18 pairs (good). Overall: **GREEN**.",
      createdAt: "2025-12-28T17:00:00+03:00",
    },
    {
      localId: "guv-015",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "🚨 **Incident report — near-miss, Feb 14, 2026** 🚨\n\nToday around 21:40, during prototype cutting in the shop, the **pit blade** (8\" circular cut-off blade) on the bench saw came loose, flew off, and landed on the floor about 60cm from the nearest student. No injuries. Production stopped.\n\nImmediate actions:\n1. Saw shut down immediately (LOTO lock applied)\n2. All students cleared from the shop, mentor inspection underway\n3. Loose nut detected on the blade arbor — maintenance log warning\n4. Incident report being drafted",
      createdAt: "2026-02-14T22:08:00+03:00",
    },
    {
      localId: "guv-016",
      channelId: CH_GUV,
      authorUserId: U_BUGRA,
      content: "First: nobody got hurt, thank god. Now let's walk through this with discipline:\n1. **Incident report** filed in SAFE-7 format tonight\n2. Every student who uses the saw gets **re-briefed tomorrow**\n3. **Lockout-tagout (LOTO) policy** — has been loose so far, we're formalizing it now\n4. Saw maintenance records reviewed — do we know when the nut was last torqued?",
      createdAt: "2026-02-14T22:20:00+03:00",
      replyToLocalId: "guv-015",
    },
    {
      localId: "guv-017",
      channelId: CH_GUV,
      authorUserId: null,
      agentGenerated: true,
      agentType: "channel-agent",
      juryReflexKind: "proof_demand",
      content: "Has an incident report been written for this near-miss? Filed in FRC SAFE-7 format? Time of incident, layout, witnesses, root cause, corrective action, prevention step — without all of these, a Safety Award submission has a gap. — PitOS",
      createdAt: "2026-02-14T22:35:00+03:00",
      replyToLocalId: "guv-016",
    },
    {
      localId: "guv-018",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "SAFE-7 file: https://drive.goat.../safe7-2026-001.pdf\n\nContents:\n- Time, location, witnesses (3 students + 1 mentor)\n- Root cause: blade arbor nut last torqued 4 weeks ago, loosened by vibration; no periodic check procedure existed\n- Corrective: LOTO + torque check at every startup, signed in the log book\n- Preventive: torque-check schedule for all rotating tools (weekly)",
      createdAt: "2026-02-15T01:18:00+03:00",
      replyToLocalId: "guv-017",
    },
    {
      localId: "guv-019",
      channelId: CH_GUV,
      authorUserId: U_HAKAN,
      content: "Solid report. **LOTO policy** draft:\n- Personal lock + tag set next to every machine\n- Before maintenance/cleaning, machine must be stopped and energy isolated before locking\n- Whoever applies the lock writes their name + date — only they can remove it\n- 2-minute visual check before use — nut, blade condition, cabling\n\nWe're running a workshop this weekend, mandatory for every student.",
      createdAt: "2026-02-15T10:05:00+03:00",
      replyToLocalId: "guv-018",
    },
    {
      localId: "guv-020",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Workshop done, 16 students passed, 2 students wrapping up tomorrow with an extra session. LOTO locks (personal) ordered — not from AndyMark, from a local hardware store, 18 sets 🔒",
      createdAt: "2026-02-22T15:40:00+03:00",
      replyToLocalId: "guv-019",
    },
    {
      localId: "guv-021",
      channelId: CH_GUV,
      authorUserId: U_DENIZ,
      content: "Are we doing LOTO at the pit during competition too? We need a clear rule for cutting motor power before bumper removal.",
      createdAt: "2026-02-22T16:08:00+03:00",
      replyToLocalId: "guv-020",
    },
    {
      localId: "guv-022",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Yes, in the pit too — no repairs while the robot's main breaker is on. Required sequence: breaker off + battery removed + 30 sec wait (capacitors discharge). Pit Captain and Safety Captain enforce this.",
      createdAt: "2026-02-22T16:22:00+03:00",
      replyToLocalId: "guv-021",
    },
    {
      localId: "guv-023",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "**Pre-Bosphorus safety walk** results (Mar 4):\n- ✅ Z87.1 goggles on every student\n- ✅ Pit gear LOTO-compatible\n- ✅ Fire extinguisher + first aid ready in the case\n- ✅ Emergency contact card (mentors + venue medical) printed, one copy per person\n- ✅ Backup printout of the SAFE-7 report in the sponsor folder\n\nAll our anchors for the Safety Award at the venue are solid.",
      createdAt: "2026-03-04T20:00:00+03:00",
    },
    {
      localId: "guv-024",
      channelId: CH_GUV,
      authorUserId: U_BUGRA,
      content: "Kağan Bahadır's battery log is in Notion: https://notion.../kbd-battery-log — at the regional, every charge cycle, voltage, and temperature is logged individually. This kind of discipline is the anchor we want for the Safety Award, the thing we hand to the judge.",
      createdAt: "2026-03-04T20:18:00+03:00",
      replyToLocalId: "guv-023",
    },
    {
      localId: "guv-025",
      channelId: CH_GUV,
      authorUserId: U_ZEYNEP,
      content: "Daily walk list as Safety Captain at the regional:\n- Morning pit open: equipment + PPE check\n- Before every repair: LOTO + breaker\n- Evening close: goggles count, charge status, spare batteries\n- If an incident happens: SAFE-7 form + notify Kağan in < 15 min",
      createdAt: "2026-03-05T22:50:00+03:00",
    },
    {
      localId: "guv-026",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Bosphorus, day of Mar 6: zero incidents, zero complaints. 0 incident, 0 near-miss on the books. The pit crew is disciplined — Zeynep especially, getting verbal confirmation of the breaker check before every repair.",
      createdAt: "2026-03-06T22:30:00+03:00",
    },
    {
      localId: "guv-027",
      channelId: CH_GUV,
      authorUserId: U_KAGAN,
      content: "Season closing report (summary):\n- 1 incident report (near-miss, February) → fully documented, root cause resolved\n- 4 quarterly audits, all GREEN\n- 18 LOTO locks active, 100% of students trained\n- 0 competition incidents\n- Z87.1 enforcement at 100%\n\nFull report uploaded to the mentors' panel. Safety is a strong theme heading into end-of-season Exit Interviews.",
      createdAt: "2026-04-12T18:00:00+03:00",
    },
    {
      localId: "guv-028",
      channelId: CH_GUV,
      authorUserId: U_BUGRA,
      content: "Kağan, I've been with this team for 6 years and **this year our safety culture is the most mature it's ever been in our history**. The near-miss was a painful wake-up call, but the LOTO policy + audit cadence + student training laid solid foundations. Thank you.",
      createdAt: "2026-04-12T19:22:00+03:00",
      replyToLocalId: "guv-027",
    },
  ],

  tasks: [
    {
      localId: "task-kop-001",
      channelId: CH_KIT,
      title: "Send FIRST replacement request for missing parts (2 Krakens + 3 PWM)",
      description: "Packing slip + photos + Inventory Discrepancy form, CC Hakan. Post the ticket number back in the thread.",
      assignedToUserId: U_DENIZ,
      assignedByUserId: U_HAKAN,
      createdViaLocalMessageId: "kop-006",
      deadline: "2026-01-11T23:59:00+03:00",
      status: "done",
      completedAt: "2026-01-22T15:47:00+03:00",
      createdAt: "2026-01-10T11:31:00+03:00",
    },
    {
      localId: "task-kop-002",
      channelId: CH_KIT,
      title: "Swerve module CAD comparison (MK4i vs MAXSwerve)",
      description: "Both versions in Onshape, compare dimensions / compatibility / cost. Will feed into the decision.",
      assignedToUserId: U_ZEYNEP,
      assignedByUserId: U_DENIZ,
      createdViaLocalMessageId: "kop-013",
      deadline: "2026-01-12T20:00:00+03:00",
      status: "done",
      completedAt: "2026-01-12T19:33:00+03:00",
      createdAt: "2026-01-12T11:02:00+03:00",
    },
    {
      localId: "task-kop-003",
      channelId: CH_KIT,
      title: "Update KOP inventory table for the sponsor report",
      description: "187 SKUs, 4 categories. KOP + COTS + donated parts. Include a pivot table for the sponsor report.",
      assignedToUserId: U_EREN,
      assignedByUserId: U_AYSE,
      createdViaLocalMessageId: "kop-026",
      deadline: "2026-01-27T23:59:00+03:00",
      status: "done",
      completedAt: "2026-01-24T20:54:00+03:00",
      createdAt: "2026-01-24T09:30:00+03:00",
    },
    {
      localId: "task-pit-001",
      channelId: CH_PIT,
      title: "Pit Display Board design + print",
      description: "4-panel layout: tech summary, season storyline, team identity, Impact. Figma mockup → approval → print shop.",
      assignedToUserId: U_EREN,
      assignedByUserId: U_DENIZ,
      createdViaLocalMessageId: "pit-022",
      deadline: "2026-03-01T23:59:00+03:00",
      status: "done",
      completedAt: "2026-03-01T14:20:00+03:00",
      createdAt: "2026-02-27T16:00:00+03:00",
    },
    {
      localId: "task-pit-002",
      channelId: CH_PIT,
      title: "6-minute repair drill series",
      description: "At least 4 drills across the season, end-of-season target under 6 min. First drill on Feb 21.",
      assignedToUserId: U_DENIZ,
      assignedByUserId: U_HAKAN,
      createdViaLocalMessageId: "pit-013",
      deadline: "2026-03-05T23:59:00+03:00",
      status: "done",
      completedAt: "2026-03-06T14:55:00+03:00",
      createdAt: "2026-02-15T20:12:00+03:00",
    },
    {
      localId: "task-pit-003",
      channelId: CH_PIT,
      title: "Switch tool wall to carabiner system + order spare tools",
      description: "Replace the missing scissors with 2 spares + clip every tool down with a carabiner. Loss prevention.",
      assignedToUserId: U_MERVE,
      assignedByUserId: U_DENIZ,
      createdViaLocalMessageId: "pit-018",
      deadline: "2026-03-04T23:59:00+03:00",
      status: "done",
      completedAt: "2026-02-26T10:42:00+03:00",
      createdAt: "2026-02-25T11:15:00+03:00",
    },
    {
      localId: "task-guv-001",
      channelId: CH_GUV,
      title: "Design quarterly Safety Inventory Audit format + schedule",
      description: "Notion page, mentor + 1 student paired, last week of each quarter. First audit on Dec 28.",
      assignedToUserId: U_KAGAN,
      assignedByUserId: U_HAKAN,
      createdViaLocalMessageId: "guv-006",
      deadline: "2025-09-26T23:59:00+03:00",
      status: "done",
      completedAt: "2025-09-19T11:08:00+03:00",
      createdAt: "2025-09-18T17:35:00+03:00",
    },
    {
      localId: "task-guv-002",
      channelId: CH_GUV,
      title: "Pit blade near-miss incident report in SAFE-7 format",
      description: "Time, location, witnesses, root cause, corrective + preventive action. Upload to Drive.",
      assignedToUserId: U_KAGAN,
      assignedByUserId: U_BUGRA,
      createdViaLocalMessageId: "guv-016",
      deadline: "2026-02-15T08:00:00+03:00",
      status: "done",
      completedAt: "2026-02-15T01:18:00+03:00",
      createdAt: "2026-02-14T22:20:00+03:00",
    },
    {
      localId: "task-guv-003",
      channelId: CH_GUV,
      title: "LOTO workshop (mandatory, all students)",
      description: "Weekend session, Hakan + Kağan run it together. Distribute personal locks/tags + walk through torque-check procedure.",
      assignedToUserId: U_KAGAN,
      assignedByUserId: U_HAKAN,
      createdViaLocalMessageId: "guv-019",
      deadline: "2026-02-23T23:59:00+03:00",
      status: "done",
      completedAt: "2026-02-22T15:40:00+03:00",
      createdAt: "2026-02-15T10:05:00+03:00",
    },
  ],

  decisions: [
    {
      localId: "dec-kop-001",
      sourceLocalMessageId: "kop-015",
      decision: "Adopt SDS MK4i x4 as the swerve module, ordered through AndyMark.",
      rationale:
        "Last season's leftover flange and bevel gear inventory is compatible with MK4i (so we're not starting from zero); AndyMark lead time is 7-10 days to TR vs MAXSwerve direct from REV at 14+ days; total cost ~$1620 vs MAXSwerve $1740 + extra bumper plates; weight delta is ~140g per module, negligible.",
      alternativesConsidered:
        "REV MAXSwerve x4 (newer generation, more modern but needs new bumper plates + 14+ day lead time); WCP Swerve X (out of budget + WCP TR customs averages 17 days); sticking with the existing tank drive (failed in the 2024 season, strategy team rejected it).",
      contextAtTime:
        "Right after Jan 2026 kickoff, with a game manual that demands high mobility on the field; 6-week build window, lead time is on the critical path.",
      decidedAt: "2026-01-12T20:11:00+03:00",
    },
    {
      localId: "dec-kop-002",
      sourceLocalMessageId: "kop-019",
      decision: "AndyMark is the default COTS supplier; WCP only for parts without an equivalent; orders ≥ $500 require 3 mentor approvals.",
      rationale:
        "Last season's data: AndyMark 7 orders averaged 9 days; WCP 3 orders averaged 17 days, with one taking 23 days (the bumper corners). Consistent lead times are critical during the build window. Multi-mentor approval over $500 reduces single-point-of-decision risk.",
      alternativesConsidered:
        "AndyMark only (leaves a gap for WCP-exclusive parts); a local TR distributor (insufficient quality + parts variety); case-by-case evaluation per order (time-consuming + inconsistent).",
      contextAtTime:
        "After the MK4i decision, we needed clarity on supplier policy; multiple COTS orders are expected throughout the season.",
      decidedAt: "2026-01-12T20:42:00+03:00",
    },
    {
      localId: "dec-pit-001",
      sourceLocalMessageId: "pit-012",
      decision: "Pit crew split into 7 roles (Pit Captain, Safety Captain, Mechanical 1-2, Electrical 1, Software 1, Tools/Inventory, Pit Display/PR); one assignment per role, double-roling banned.",
      rationale:
        "Last season at Bosphorus, one person was given two roles, which delayed missing-tool detection and partially cost us a judge briefing. One assignment per role prevents attention fragmentation. Hakan's pushback (Tools/Inventory + PR as a double role won't work) was confirmed.",
      alternativesConsidered:
        "Flexible rotation (last season's mistake, tried and failed); a larger pit crew (field rules cap pit headcount at 6); pulling drive team into pit work (fatigue + match prep conflict).",
      contextAtTime:
        "February 2026, three weeks out from Bosphorus on Mar 6-8; lesson coming out of last season's retrospective.",
      decidedAt: "2026-02-13T12:18:00+03:00",
    },
    {
      localId: "dec-guv-001",
      sourceLocalMessageId: "guv-019",
      decision: "Lockout-Tagout (LOTO) policy formally adopted; mandatory workshop + personal lock/tag set distribution for every student.",
      rationale:
        "Root cause analysis of the Feb 14, 2026 pit blade near-miss identified a loose blade-arbor nut + the absence of a periodic check procedure. LOTO + a torque-check schedule prevents recurrence; also serves as an anchor for the FRC Safety Award.",
      alternativesConsidered:
        "Continue with the existing loose procedure (unacceptable, recurrence risk); machines used only under mentor supervision (limits student learning, doesn't scale); banning machines entirely (impossible given the project).",
      contextAtTime:
        "Within 24 hours of the near-miss, coordinated by Hakan + Kağan; mid-build season, the SAFE-7 incident report had just been filed.",
      decidedAt: "2026-02-15T10:05:00+03:00",
    },
    {
      localId: "dec-guv-002",
      sourceLocalMessageId: "guv-007",
      decision: "Quarterly Safety Inventory Audit cadence kicked off (mentor + 1 student paired, last week of each quarter).",
      rationale:
        "During the September 2025 battery drill, we caught an expired eyewash bottle — that pushed us toward a proactive schedule instead of a reactive one. The paired structure (mentor + student) ensures knowledge transfer; rotating students spreads the safety culture. Aligned with Buğra's \"habit vs enforcement\" framing.",
      alternativesConsidered:
        "A single annual audit (insufficient given equipment lifespan); mentor-only audits (misses a student learning opportunity); event-driven audits (reactive, the actual problem).",
      contextAtTime:
        "September 2025, four months ahead of season kickoff; KOP hadn't shipped yet, a quiet period for shop maintenance.",
      decidedAt: "2025-09-19T11:08:00+03:00",
    },
  ],
};
